server:
  port: 9090
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: finaltask
  datasource:
    url: jdbc:mysql://localhost:3306/finaltask?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: akademi4
    password: 12345
    hikari:
      connection-timeout: 3000000
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialet: org.hibernate.dialect.MySQL5Dialect


